server:
  port: 8080

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:5173"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true

      discovery:
        locator:
          enabled: true

      routes:

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**


        - id: exam-service
          uri: lb://exam-service
          predicates:
            - Path=/exam-service/**



  output:
    ansi:
      enabled: ALWAYS


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 3

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "

#Here you can use circuit breaker for fault tolerance





