

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 3




spring:
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:h2:mem:exam-service
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  application:
    name: exam-service
  threads:
    virtual:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    allow-circular-references: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans


logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "

#Here you can use circuit breaker for fault tolerance
