server:
  port: 8761
spring:
  output:
    ansi:
      enabled: ALWAYS
  threads:
    virtual:
      enabled: true

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans


logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "